import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-white dark:bg-black`}>
        <Providers>
          <Navbar />
          <div className="h-[calc(100vh-48px)] flex flex-col justify-between">
            {children}
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}

//added suppress hydrating for it so it don't give error when load the dark mode according the system
